/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TianZiGeCell: typeof import('./src/components/TianZiGeCell.vue')['default']
    TianZiGeGrid: typeof import('./src/components/TianZiGeGrid.vue')['default']
    TianZiGeWriter: typeof import('./src/components/TianZiGeWriter.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanShareSheet: typeof import('vant/es')['ShareSheet']
  }
}

// For TSX support
declare global {
  const TianZiGeCell: typeof import('./src/components/TianZiGeCell.vue')['default']
  const TianZiGeGrid: typeof import('./src/components/TianZiGeGrid.vue')['default']
  const TianZiGeWriter: typeof import('./src/components/TianZiGeWriter.vue')['default']
  const VanActionBar: typeof import('vant/es')['ActionBar']
  const VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
  const VanButton: typeof import('vant/es')['Button']
  const VanField: typeof import('vant/es')['Field']
  const VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanShareSheet: typeof import('vant/es')['ShareSheet']
}