/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TianZiGeCell: typeof import('./src/components/TianZiGeCell.vue')['default']
    TianZiGeGrid: typeof import('./src/components/TianZiGeGrid.vue')['default']
    TianZiGeWriter: typeof import('./src/components/TianZiGeWriter.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}

// For TSX support
declare global {
  const TianZiGeCell: typeof import('./src/components/TianZiGeCell.vue')['default']
  const TianZiGeGrid: typeof import('./src/components/TianZiGeGrid.vue')['default']
  const TianZiGeWriter: typeof import('./src/components/TianZiGeWriter.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
}